/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_appsync_graphqlEndpoint": "https://6hommtpbhvarnmx426uog75gma.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4ebzodkvpvaizh7yjysoe2ifoe",
    "aws_cloud_logic_custom": [
        {
            "name": "adminRESTv1",
            "endpoint": "https://t7lifkbft5.execute-api.ca-central-1.amazonaws.com/beta",
            "region": "ca-central-1"
        },
        {
            "name": "customerRESTv1",
            "endpoint": "https://2nye6h26q8.execute-api.ca-central-1.amazonaws.com/beta",
            "region": "ca-central-1"
        },
        {
            "name": "deliveryPartnerRESTv1",
            "endpoint": "https://ayk2ma9olj.execute-api.ca-central-1.amazonaws.com/beta",
            "region": "ca-central-1"
        },
        {
            "name": "publicRESTv1",
            "endpoint": "https://dw13ig1td3.execute-api.ca-central-1.amazonaws.com/beta",
            "region": "ca-central-1"
        },
        {
            "name": "stripeWebhookRESTv1",
            "endpoint": "https://jjo1s4o59l.execute-api.ca-central-1.amazonaws.com/beta",
            "region": "ca-central-1"
        },
        {
            "name": "appRESTv1",
            "endpoint": "https://jglxl5mnc6.execute-api.ca-central-1.amazonaws.com/beta",
            "region": "ca-central-1"
        }
    ],
    "aws_cognito_identity_pool_id": "ca-central-1:402dd4ab-e458-435b-8843-421599917756",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_93iuOjbwV",
    "aws_user_pools_web_client_id": "1lo3062r53niga21u0am7omdkt",
    "oauth": {
        "domain": "inapulsebeta-beta.auth.ca-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://www.inapulse.com",
        "redirectSignOut": "https://www.inapulse.com",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "FACEBOOK",
        "GOOGLE",
        "APPLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "inapulsedeliveryimage130130-beta",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;

